name: Rust_CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build test
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check formatting
        run: cargo fmt --all -- --check
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
            with:
              commit_message: Apply Code Formatter Change
              ref: ${{ github.head_ref }}
